let ism=alert("Assalomu alekum") 
let ali=prompt("Assalomu alekum")
let  iltimos=alert("alik ob qoyin iltimos")
let  nik=prompt("Ismiz nima?")
let  familya=prompt("Familyangiz nima?")
let  age=prompt("Yoshingiz nechida")
let bg=prompt("backgoround img yaxwi chiqibtimi?")
let raxmat=alert('raxmat')
let  follow=prompt("Biz bilan birga bo'lishni xohlismi?")
let  click=alert("Xoziroq Click programasin yuklab olin")
let  money=prompt("Undan song +998935197766 raqimga paynet qvorin brat")
let   brat=prompt("So'kmena faqat")
let  happy=alert("Atak xursan bo'lardim")
console.log(ism, ali, iltimos, nik, familya, age, bg, raxmat, follow, click, money, brat,happy)